### ISSUE TITLE
Api 2.1 a unikalność extOrderId

### ISSUE THREAD

**Issue by krzaczek** [PayU/openpayu_php#28]
Witam,

Nowa werjsa bibloteki wprowadza unikalność parametru extOrderId względem POS. Moje pytanie brzmi jak pozwolić użytkownikowi zapłacić "ponownie" za zamówienie jeśli np płatnośc zostanie anulowana lub wystąpi jakiś błąd.

Do tej pory działaliśmy tak że w extOrderId przekazywaliśmy id zamówienia z naszego sklepu. Jeśli status płatności był np Anulowany pozwalaliśmy klientowi "zapłać ponownie". W nowym API jest to nie możliwe bo próba utworzenia nowej płatności z tym samym extOrderId kończy się błędem.

ERROR: OpenPayU_Result::__set_state(array( 'status' => 'ERROR_ORDER_NOT_UNIQUE', 'error' => '', 'success' => 0, 'request' => '', 'response' => stdClass::__set_state(array( 'orderId' => '7H1B6KQMBX140828GUEST000P01', 'extOrderId' => '11964', 'status' => stdClass::__set_state(array( 'statusCode' => 'ERROR_ORDER_NOT_UNIQUE', 'code' => '110', 'codeLiteral' => 'ORDER_NOT_UNIQUE', 'statusDesc' => 'Order with given extOrderId already exists', )), )), 'sessionId' => '', 'message' => '', 'countryCode' => '', 'reqId' => '', ))

Jak w takim przypadku pozwolić userowi zapłacić ponownie za to samo zamówienie lub dopłacić do zamówienia - w oby przypadkach pole extOrderId będzie takie same .. czyli będzie zawierać id zamówienia którego dotyczy płatność

**Comment by maicher** [comment]
Problem może powodować występowanie znaków `/` w polu extOrderId.
Po usunięciu slashy z ERROR_ORDER_NOT_UNIQUE przestał występować.
