### ISSUE TITLE
401 error not being handled properly

### ISSUE THREAD

**Issue by Agares** [PayU/openpayu_php#35]
Hi, when in \OpenPayU_Order::create($order) I get 401 error, then instead of Exception, I get:
Notice: Trying to get property of non-object in /www/vendor/openpayu/openpayu/lib/OpenPayU/Http.php line 107

**Comment by jaygridley** [comment]
Same issue here. $message object could be null. Please fix it.

**Comment by regdos** [comment]
Please check with commit https://github.com/PayU/openpayu_php/commit/89bd30455807615b55d2aa9c2142d8f85431178d
