### ISSUE TITLE
OpenPayU_HttpCurl has hardcoded TLSv1 cipher which fails with NSS module: 'Unknown cipher in list: TLSv1'

### ISSUE THREAD

**Issue by ChieftainY2k** [PayU/openpayu_php#38]
**The problem:**

OpenPayU_HttpCurl has hard coded cipher list TLSv1 which causes curl to fail when you use PHP with NSS library instead of OpenSSL. We experienced this on multiple servers. 

OpenPayU_HttpCurl line 65 is:
curl_setopt($ch, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

This results with exception 'OpenPayU_Exception_Network' with message 'Unknown cipher in list: TLSv1'

**Reason:**

According to the curl libs documentation there is difference in ciphers list depending on whether you use OpenSSL or NSS module:
http://curl.haxx.se/libcurl/c/CURLOPT_SSL_CIPHER_LIST.html

For OpenSSL and GnuTLS valid examples of cipher lists include 'RC4-SHA', ´SHA1+DES´, 'TLSv1' and 'DEFAULT'. 

Source: http://www.openssl.org/docs/apps/ciphers.html

'For NSS, valid examples of cipher lists include 'rsa_rc4_128_md5', ´rsa_aes_128_sha´, etc. 

Source: http://curl.haxx.se/libcurl/c/CURLOPT_SSL_CIPHER_LIST.html

**Solution:**

With NSS module use proper cipher symbol, for example:
curl_setopt($ch, CURLOPT_SSL_CIPHER_LIST, 'rsa_aes_256_sha');

**Library modifications:**

1) Modify OpenPayU_Configuration so that it passes override params to the OpenPayU_HttpCurl
OR
2) Use dependency injection to change defaults in OpenPayU_HttpCurl

**Comment by agnagna** [comment]
If you have it implemented, pull request is welcome :)

**Comment by regdos** [comment]
Remove in https://github.com/PayU/openpayu_php/commit/40cc9ab3f0638f5894f65745d88b8debdd299193
