### ISSUE TITLE
Problem z OrderNotify.php

### ISSUE THREAD

**Issue by piotrmalek** [PayU/openpayu_php#40]
Witam. Od kilku dni PayU nie wysyła powiadomień na OrderNotify.php. Ponieważ jestem w trakcie prac nad serwisem wrzuciłem całą nową paczkę openpayu_php na serwer w osobnej domenie. 
Wyedytowałem plik examples/v2/order/OrderNotify.php i po
require_once realpath(dirname(__FILE__)) . '/../../../lib/openpayu.php';
require_once realpath(dirname(__FILE__)) . '/../../config.php';
dodałem:
$fpa = fopen(date("Ymd-His")."-".rand(100, 999).".test", "w");
fwrite($fpa, date("Y-m-d H:i:s") . "\xA"); 
fwrite($fpa, $_SERVER['REMOTE_ADDR']. "\xA");
fclose($fpa);

Gdy wywołam plik z przeglądarki skrypt tworzy plik (ex. 20150119-175252-414.test), natomiast jak użyję OrderForm.php lub OrderCreate.php plik nie jest tworzony - wygląda jakby PayU nie wysyłało powiadomieć o zmianie statusu stransakcji.
OrderForm.php zmodyfikowałem następująco:
$order['notifyUrl'] = 'http://domena.pl'.dirname($_SERVER['REQUEST_URI']).'/OrderNotify.php';
$order['continueUrl'] = 'http://domena.pl'.dirname($_SERVER['REQUEST_URI']).'/../../layout/success.php';

Płatność przechodzi jak należy, po "opłaceniu" transakcji PayU przekierowuje na success.php.
Czy robię coś źle, czy jest jakiś błąd po stronie PayU?

Piotr Małek

**Comment by agnagna** [comment]
Witam,
najlepiej skontaktować się z biurem obsługi technicznej tech@payu.pl i w zgłoszeniu podać swój numer posa.

Pozdrawiam,
Agnieszka

**Comment by emendelski** [comment]
@agnagna nie tylko @piotrmalek ma takie problemy.
Więc odsyłanie do supportu, który zwleka z pomocą do niczego nie prowadzi.

@piotrmalek jeśli byś znalazł rozwiązanie daj znać, bo mamy identyczny błąd.

**Comment by piotrmalek** [comment]
Taki miałem plan :) Napisałem do supportu i czekam na odpowiedź.

**Comment by Setitch** [comment]
Zaczynam wierzyć, że rozwiązaniem jest po prostu korzystanie z konkurencji. To już nie pierwszy przypadek, że coś co normalnie działało nagle przestaje, albo z głupia pęk zmieniają sobie całe api - nie jest zbyt przyjemne - w czasie korzystania z openpayu trzy razy w ciągu 2 miesięcy miałem takie problemy...

**Comment by agnagna** [comment]
@piotrmalek:
* jaką wersję SDK Pan posiada?
* czy sklep jest już dostępny pod publiczną domeną? Jesli tak, to czy mógłby pad ją podać?
* czy wcześniej udawało się odbierać poprawnie notyfikacje od PayU? 

@emendelski jesli ma Pan podobny problem, proszę również o odpowiedzi na powyższe pytania. Spróbuję pomóc.

**Comment by agnagna** [comment]
Proszę jeszcze upewnić się, że mają Państwo w php.ini ustawiony parametr allow_url_fopen = 1.

**Comment by Setitch** [comment]
Gdyby nie mieli tego ustawionego, to by nie mogli wogóle korzystać ze skryptu - jakkolwiek...

**Comment by piotrmalek** [comment]
Otrzymałem odpowiedź od PayU:

"Domena położona jest w OVH.

Z naszej analizy wynika, że nie możemy uzyskać połączenia z naszej adresacji. Próby połączenia kończą się timeoutami.

Dodam, że otrzymaliśmy więcej zgłoszeń tego typu - wszyscy zgłaszający klienci korzystają z usług OVH. "

Teraz pozostaje mi walczyć w OVH. 
Czy szanowni koledzy też mają hosting w OVH?

**Comment by emendelski** [comment]
@piotrmalek też OVH.

**Comment by piotrmalek** [comment]
OVH twierdzi że pracują nad problemem który pojawił się po zmianie szyfrowania przez PayU. Pozostaje nam czekać...

P.S. OVH nie podaje nawet przybliżonego terminu wprowadzenia zmian :(

**Comment by Setitch** [comment]
Czyli jakaś sobie zmiana payu - kolejna.

**Comment by agnagna** [comment]
Zmiany po stronie PayU spowodowane sa względami bezpieczeństwa: https://www.us-cert.gov/ncas/alerts/TA14-290A

Pozdrawiam,
Agnieszka

**Comment by Setitch** [comment]
Są, tylko, że nie pierwszy raz zmieniacie coś sobie bez niczego powodówjąc ze stare wersje nie działają nikomu.

**Comment by emendelski** [comment]
@agnagna @openpayu @techpayu 
Czy cokolwiek się zmieniło jeśli chodzi o wspomniane timeouty? Czy wiadomo coś nt. rozwiązania powyższego problemu?

@piotrmalek @Setitch 
Udało Wam się jakoś ominać problem?

**Comment by agnagna** [comment]
Najprawdopodobniej problem leży po stronie dostawcy usług hostingowych.

**Comment by gskgrek** [comment]
Ale co jest tym problemem? Nie pojde do histingu przeciez z informacja ze payu mi nie dziala. Musze im dac jakis konkret.
Co ciekawe do niedawna wszystko gralo i nagle payu nie moze wywolac zwyklego linka do php? :|
