### ISSUE TITLE
niedocierające powiadomienia

### ISSUE THREAD

**Issue by think-01** [PayU/openpayu_php#50]
Witam, 
zgodnie z dokumentacją i samplami w repozytorium przesyłam zamówienie metodą OpenPayU_Order::create ,używam do tego testowych danych autoryzacyjnych podanych w dokumentacji. Struktura przed wywołaniem OpenPayU_Order::create wygląda następująco:

```
Array
(
    [notifyUrl] => https://t01.pl/payu-test
    [continueUrl] => http://127.0.0.1/tense/bodychief.pl/index.php/user_panel/history
    [customerIp] => 83.24.94.200
    [merchantPosId] => 145227
    [description] => Zamówienie
    [currencyCode] => PLN
    [products] => Array
        (
            [0] => Array
                (
                    [name] => STANDARD 500 KCAL
                    [unitPrice] => 510
                    [quantity] => 1
                )

        )

    [totalAmount] => 510
    [buyer] => Array
        (
            [email] => slawek+abc@******.pl
            [phone] => +48227777777
            [firstName] => imie
            [lastName] => nazwisko
        )

)
```

cały proces, łącznie z wysłaniem przez payu statusu zamówienia na email przebiega prawidłowo lecz adres notifyUrl nigdy nie zostaje wywołany

pod adresem podanym w notifyUrl mam następujący ( działający i sprawdzony zarówno dla GET jak i POST ) skrypt:

```
<?php
$fn = "./f/".time().".txt";
file_put_contents( $fn, file_get_contents("php://input"));
?>
```

w czym problem?

**Comment by regdos** [comment]
Na podany przez Pana adres w [notifyUrl] zostaje wysłana notyfikacja, następuje jednak przekierowanie 301. 
Proszę sprawdzić konfigurację serwera.
W przyszłości w takich sprawach prosze o kontakt z BOK.
