### ISSUE TITLE
403 - bledna autentyfikacja

### ISSUE THREAD

**Issue by dkonopka** [PayU/openpayu_php#51]
Witajcie,

Uzywam formularza examples/v2/order/OrderForm.php. Dla testowego formularza dziala wporzadku, jednak gdy wstawiam swoje dane punktu platnosci (pos id i drugi klucz md5), to przy platnosci otrzymuje 403.

https://secure.payu.com/pl/standard/co/status/forbidden
Dostęp do strony jest zabroniony.

W czym moze tkwic problem?

**Comment by regdos** [comment]
Problem nie leży po stronie SDK. Proszę o kontakt z BOK z podaniem numeru POS-a.

**Comment by assghard** [comment]
Mam ten sam problem. Proszę o info czy problem został rozwiązany i jak?

**Comment by regdos** [comment]
Proszę o kontakt z BOK gdyż to jest najszybsza metoda na rozwiązanie Pana problemu.

**Comment by dkonopka** [comment]
@assghard  Jak dobrze pamiętam, błędem było brak wczytywania zmiennych parametrów zgodnie z porządkiem alfabetycznym :)
