### ISSUE TITLE
Błąd autoryzacji

### ISSUE THREAD

**Issue by lipiluk** [PayU/openpayu_php#52]
Witam, jako, że nie mogłem odpisać w poprzednim temacie tyczącym tego samego błędu, jestem zmuszony do napisania kolejnego.
Korzystam z najnowszej wersji SDK, mój MerchantPosId: 164771 .
Podczas uzytkowania Examples --> CreateOrder.php , wszystko działa jak należy, tworzona jest nowa płatność. Kiedy jednak zmieniam PosId na swoje, SignatureKey na podany w PayU, nowa płatność nie powstaje. Wyrzuca mi błąd:
```php
string(550) "exception 'OpenPayU_Exception_Authorization' with message ' - ' in /vol/www/whitemobileteles/platnosci_test/lib/OpenPayU/Http.php:97
Stack trace:
#0 /vol/www/whitemobileteles/platnosci_test/lib/OpenPayU/v2/Order.php(178): OpenPayU_Http::throwHttpStatusException(401, Object(OpenPayU_Result))
#1 /vol/www/whitemobileteles/platnosci_test/lib/OpenPayU/v2/Order.php(50): OpenPayU_Order::verifyResponse(Array, 'OrderCreateResp...')
#2 /vol/www/**************/platnosci_test/platnosci/v2/order/OrderCreate.php(68): OpenPayU_Order::create(Array)
#3 {main}"
```
oraz:
```php
Fatal error: Call to a member function getStatus() on a non-object in /vol/www/*************/platnosci_test/platnosci/v2/order/OrderCreate.php on line 99
```php

Proszę o pomoc.

**Comment by regdos** [comment]
POS na którym Panoperuje jest typu Classic. 
W przypadku SDK wymagany jest POS typu REST. Proszę założenie nowego POS-a typu REST z poziomu panelu.
