### ISSUE TITLE
Brak zakończenia wysyłania do Notify

### ISSUE THREAD

**Issue by marczaq** [PayU/openpayu_php#53]
Mam problem. 
Integruję swój system sprzedażowy za pomocą klas z repozytorium i mam problem z ciągłym odpowiadaniem od PayU.
Moja funkcja na notify:

    public function notify()
    {
        $this->autoRender = false;
        App::import('Lib', 'OpenPayU' . DS . 'OpenPayU_Exception');
        App::import('Lib', 'OpenPayU' . DS . 'OpenPayU_Order');
        $body = file_get_contents('php://input');
        $data = trim($body);
        CakeLog::warning('Data', 'orders');
        CakeLog::warning($data, 'orders');
        
        try {
            $response = OpenPayU_Order::consumeNotification($data);
            $r1 = $response->getResponse()->order->status; //NEW PENDING CANCELLED REJECTED COMPLETED WAITING_FOR_CONFIRMATION
            CakeLog::warning('Doszedlem', 'orders');
            CakeLog::warning($r1, 'orders');

        } catch (OpenPayU_Exception $e) {
            CakeLog::error($e->getMessage(), 'orders');
        }
        header("HTTP/1.1 200 OK");
    }

Dodaję do log-a kolejne odpowiedzi od PayU. I wysyłane są one ciągle. 
Wg. dokumentacji header("HTTP/1.1 200 OK") powinno zaprzestać wysyłania odpowiedzi. Plik log-a ciągle jednak rośnie.

Dodam, że działam na danych tesowych.

**Comment by regdos** [comment]
Potrzebne jest więcej danych tj. adres URL na który zostaje wysyłana notyfikacja

**Comment by marczaq** [comment]
Problem został już rozwiązany.

**Comment by devolkpl** [comment]
Mam podobny problem. Zakładając, że na koncie produkcyjnym lecz przy testowej metodzie płatności takie powiadomienia powinienem odbierać. 
Tak jakby OrderNotify.php z przykładu nie był wcale wywoływany.

**Comment by regdos** [comment]
Proszę o kontakt z BOK z podaniem numeru POS-a, z którego Pan korzysta i opisem problemu.
