### ISSUE TITLE
Problem z OrderNotify.php

### ISSUE THREAD

**Issue by sotebuy** [PayU/openpayu_php#54]
Witam,
Dostaje taki wyjątek podczas odebrania odpowiedzi z payu w trybie testowym:
plik: OpenPayU/HttpCurl.php (linia: 69)
Wyjątek: GnuTLS recv error (-9): A TLS packet with unexpected length was received.

Pozdrawiam
Marcin Butlak

**Comment by regdos** [comment]
Proszę o podanie wersji PHP, wersji biblioteki CURL oraz wersji biblioteki SSL z CURL-a (wszystko dostępne z phpinfo())

**Comment by sotebuy** [comment]
Curl: 7.26.0 (GnuTLS/2.12.20)

**Comment by regdos** [comment]
Błąd jest związany z wersjami bibliotek. Zalecamy upgrade curl-a oraz zamianę GnuTLS na OpenSSL

**Comment by sotebuy** [comment]
Dzięki aktualizacja bibliotek pomogła.
