### ISSUE TITLE
Przekroczono maksymalną kwotę zamówienia dla wybranego kanału płatności

### ISSUE THREAD

**Issue by cve** [PayU/openpayu_php#55]
Kwota tej testowej płatności to 2000 zł, taki komunikat wyświetla się na górze po przejściu do strony PayU i wybraniu sposobu płatności PayU. 

Komunikat taki się wyświetla i nie ma możliwości dokończenia płatności w żaden inny sposób, po manualnym wycofaniu się do strony sklepu  nie przychodzą również notyfikacje, że coś poszło nie tak.

Jak reagować na tego typu błąd?

**Comment by regdos** [comment]
W przypadku transakcji testowej maksymalna kwota transakcji to 1000 zł
