### ISSUE TITLE
Order::consumeNotification

### ISSUE THREAD

**Issue by dszczer** [PayU/openpayu_php#56]
Odbieranie statusów - notyfikacji nie działa w tej wersji API, ponieważ odpowiedzi dla płatności **TESTOWYCH** (nie wiem czy dla prawdziwych też nie działa) zwracane są z podpisem z algorytmem MD5, który został już wykluczony w API 2.1, więc metoda `OpenPayU_Order::consumeNotification($data)` zawsze zwróci błąd o nieprawidłowym podpisie.

**Comment by regdos** [comment]
Algorytm MD5 został usunięty dla generowania podpisu dla formularza. `OpenPayU_Order::consumeNotification` korzysta z metody `OpenPayU_Util::verifySignature`, która obsługuje MD5 więc odbieranie notyfikacji działa prawidłowo.
