### ISSUE TITLE
NotifyURL - uszkodzony JSON

### ISSUE THREAD

**Issue by krzaczek** [PayU/openpayu_php#57]
Witam,

Jeśli klient na stronie PAYU wprowadzi dane do faktury i w nazwie użyje znaku `"` - JSON przychodzący na notifyUrl jest uszkodzony:

przykład z przed paru dni.

```json
"buyer":{
"customerId":"guest",
"email":"xxx@gmail.com",
"phone":"601XXXXXX",
"firstName":"Piotr",
"lastName":"XXXXX",
"language":"pl",
"invoice":{
"recipientName":"PHU"PIOTR" Piotr Jurek","tin":"XXX-XX-XX-XXX","eInvoiceRequested":"FALSE","street":"XXXXXX 35","postalCode":"41-500","city":"Chorzów","countryCode":"PL"
}
},
```

Na email mogę dostarczyć kompletny JSON uszkodzonej wiadomości plus informację o ID transakcji etc.

Jak widać w `recipientName` znajdują się nie dozwolone znaki `"`

Poprawnie powinno być

```json
"recipientName":"PHU\"PIOTR\" Piotr Jurek"
```

**Comment by regdos** [comment]
Dzień dobry, 

w logach naszego systemu widać, że notyfikacja jest poprawnie wysyłana 

`"recipientName":"PHU\"PIOTR\" Piotr Jurek"`

Korzysta Pan z własnej implementacji odbioru notyfikacji czy z funkcji z SDK  OpenPayU_Order::consumeNotification($data)?

**Comment by krzaczek** [comment]
Witam,

Używamy własnej implemetacji ale chyba czas się przesiąść na `OpenPayU_Order::consumeNotification`.

Okazuje się że przed `json_decode` wkradł się nam `stripslashes` (nie wiem why) i to powodowało uszkodzenie JSON. 👎 

Pawel

**Comment by regdos** [comment]
Możliwe, że kiedyś się wzorował się Pan na naszej implementacji ponieważ też mieliśmy nadmiarowe stripslashes, które zostało usunięte w https://github.com/PayU/openpayu_php/commit/a403805657cba4efcc02791f2aeda648d0461136

Najważniejsze, że udało się skutecznie znaleźć problem.

**Comment by krzaczek** [comment]
@regdos no to wszytko jasne ... dzięki za pomoc
