### ISSUE TITLE
Znaki slash `/` w polu extOrderId powodują wystąpienie blędu ERROR_ORDER_NOT_UNIQUE

### ISSUE THREAD

**Issue by maicher** [PayU/openpayu_php#61]
Przekazywałem w polu extOrderId następujące wartości: 
"XYZ/2016/871-16"
"XYZ/2016/871-17"
"XYZ/2016/871-18"
...
co powodowało występowanie ERROR_ORDER_NOT_UNIQUE.
Po usunięciu slashy '/' ERROR_ORDER_NOT_UNIQUE przestał występować.

**Comment by regdos** [comment]
extOrderId musi być unikalne w ramach jednego POS-a błąd oznacza, że na POS-ie zostało już utworzone zamówienie o podanym extOrderId. Znak slash '/' nie ma wpływu na ten błąd. Po usunięciu slashy '/' błąd przestał występować ponieważ nie było zamówienia o podanym extOrderId. 
Jeżeli spróbował by Pan założyć ponownie zamówienie z extOrderId bez slashy '/' otrzyma Pan ten sam błąd.
