### ISSUE TITLE
Problem z funkcjonalnością zwrotów

### ISSUE THREAD

**Issue by MateuszKaczmarczyk** [PayU/openpayu_php#65]
Próbuję dokonać zwrotu za pomocą OpenPayU w następujący sposób:
`$refund = OpenPayU_Refund::create(
                "5",
                "zwrot"
            );`

Zamówienie w momencie tworzenia miało przypisane 
`extOrderId= "5"`

Otrzymuję błąd:
> PHP Fatal error:  Uncaught exception 'OpenPayU_Exception_Network' with message 'DATA_NOT_FOUND - > Could not find user order [orderId=null]'

Wygląda na to, że orderId nie jest w ogóle przekazywane.

Ponadto zauważyłem, że zgodnie z dokumentacją REST API (http://developers.payu.com/pl/restapi.html#refunds) URL do zwrotów powinien kończyć się na **/refunds**, a w klasie Refund $pathUrl jest budowany w następujący sposób:
`$pathUrl = OpenPayU_Configuration::getServiceUrl().'orders/'. $refund['orderId'] . '/refund';` 
Brakuje "s" na końcu adresu.

**Comment by regdos** [comment]
Jako parametr do wykonania zwrotu należy podać  orderId a nie extOrderId czyli w Pana przypadku pierwszy parametr nie powinien być "5" tylko właściwy orderId.

**Comment by MateuszKaczmarczyk** [comment]
Czy właściwym orderId jest ten element widoczny na poniższym screenie z panelu PayU?
![image](https://cloud.githubusercontent.com/assets/16896670/21537653/d8680eac-cd94-11e6-83f2-4d721cb726c7.png)

W momencie tworzenia nie ustawiamy orderId, a jedynie extOrderId. Skąd zatem wziąć orderId?

**Comment by regdos** [comment]
To nie jest właściwy id. OrderId jest nadawane przez PayU i zwracane w odpowiedzi na OCR-a http://developers.payu.com/pl/restapi.html#creating_new_order_api 

Odnosnie refund i refunds aktualnie oba adresy są poprawne. W SDK zmienimy na refunds w najbliższym czasie.

**Comment by MateuszKaczmarczyk** [comment]
Dziękuję za pomoc, przesłałem poprawne OrderId i teraz zwroty działają.
