### ISSUE TITLE
Sandbox environment - unable to register 

### ISSUE THREAD

**Issue by drupalranger** [PayU/openpayu_php#66]
URL provided in README file doesn't work, so there is no ability to register sandbox enviro using following link: [https://secure.snd.payu.com/cp/register?lang=en](https://secure.snd.payu.com/cp/register?lang=en) - it was working in December 2016.  
I've went through developers docs and tried to find out how to register, but with no luck. 
Could you advice please?

**Comment by maciejdorsz** [comment]
Hi,

Currently we do not have sandbox accounts. We are working to make it available again, however we do not have date for it. Therefore, please integrate on our production environment. You can use pay-by-link test payment there. 

sorry to that inconvenience,
 Maciej Dorsz.

**Comment by Roen00** [comment]
Is it fixed?
So, do I understand correctly that there is no way to test the integration with sandbox environment? The only way is a test on production account?

**Comment by maciejdorsz** [comment]
Hi,

Sandbox is not ready yet. Tests are conducted on production.

Regards,
MD.

Od: Roen00 [mailto:notifications@github.com]
Wysłano: 23 lutego 2017 13:45
Do: PayU/openpayu_php
DW: Maciej Dorsz; Comment
Temat: Re: [PayU/openpayu_php] Sandbox environment - unable to register (#66)


Is it fixed?
So, do I understand correctly that there is no way to test the integration with sandbox environment? The only way is a test on production account?

**Comment by PawelMysior** [comment]
Any progress on the sandbox environment?
