### ISSUE TITLE
Jak mogę się dostać do funkcji(liczba mnoga) obiektu klasy OpenPayU_Order z poziomu przykładowego pliku OrderNotify.php

### ISSUE THREAD

**Issue by Michal0307** [PayU/openpayu_php#68]
print_r - uję obiekt $order ale nie mogę się dostać do danych z wewnątrz poza statusem :(
interesuje mnie zmienna extOrderId oraz orderId

**Comment by regdos** [comment]
Do obiektu order przy odebranej notyfikacji 
`$result = OpenPayU_Order::consumeNotification($data);`

można się dostać poprzez 

`$result->getResponse()->order`

Natomiast po wykonaniu pobrania ordera za pomocą

` $order = OpenPayU_Order::retrieve($result->getResponse()->order->orderId);` 

Zawartość obiektu order jest dostępna w 

`$response->getResponse()->orders[0]`
