### ISSUE TITLE
Credit Cards on sandbox

### ISSUE THREAD

**Issue by michalsoczynski** [PayU/openpayu_php#74]
Hello,

I tried to use Credit Cards for tests from: [http://developers.payu.com/en/overview.html](url)
for example: `4444333322221111 / 01/19 / 123`
but it doesn't work, I received from: [https://merch-prod.snd.payu.com/api/v2/token/token.json](url)
`{"status":{"statusCode":"SERVICE_NOT_AVAILABLE","codeLiteral":"CARD_TOKENIZATION_DISABLED","code":"4100"}}`

What are the correct card credentials?

**Comment by michalsoczynski** [comment]
I used for recurring payments public production test and public sandbox and the card number works. But when I sent order with:
```
["payMethods"]=>
  array(1) {
    ["payMethod"]=>
    array(2) {
      ["value"]=>
      string(32) "TOK_1JILNU8HHSUX0feRXR2WcbSV23vO"
      ["type"]=>
      string(10) "CARD_TOKEN"
    }
  }
```

I received:

```
object(stdClass)#21039 (1) {
    ["status"]=>
    object(stdClass)#21040 (2) {
      ["statusCode"]=>
      string(19) "ERROR_VALUE_INVALID"
      ["statusDesc"]=>
      string(45) "OPENPAYU_PAYMENT_CREATE_ERROR_OTHER_TEMPORARY"
    }
  }
```

Why?

**Comment by regdos** [comment]
Please contact with support - tech@payu.pl
