### ISSUE TITLE
Sandbox Access Forbidden

### ISSUE THREAD

**Issue by pajso96** [PayU/openpayu_php#77]
Kiedy tworzę nowe zamówienie ,po wejściu na przekierowanie otrzymuję kod zwrotny 403 i informację o zabronionym dostępie. Sytuacja jest identyczna zarówno na kluczach publicznych jak i prywatnie stworzonym koncie.
Kod jest bardzo prosty, nie ma zbytnio czego pomylić.

```
       $order['continueUrl'] = 'localhost/kp/web/app_dev.php';
        $order['notifyUrl'] = 'localhost/kp/web/app_dev.php';
        $order['customerIp'] = $request->getClientIp();
        $order['merchantPosId'] = $this->configuration->getPosId();
        $order['description'] = 'New card order';
        $order['currencyCode'] = 'PLN';
        $order['totalAmount'] = $card->getAmount();
        $order['extOrderId'] = $card->getCode();

        $order['products'][0]['name'] = 'Card';
        $order['products'][0]['unitPrice'] = $card->getAmount();
        $order['products'][0]['quantity'] = 1;


        $order['buyer']['email'] = $card->getBuyerEmail();
        $order['buyer']['phone'] = '123123123';
        $order['buyer']['firstName'] = $card->getBuyer();
        $order['buyer']['lastName'] = $card->getBuyer();

       try {
            $response = OpenPayU_Order::create($order);

            return $response;
        } catch (OpenPayU_Exception $e) {
            throw $e;
        }
````

Ma ktoś pojęcie co jest nie tak ?

**Comment by pajso96** [comment]
https://merch-prod.snd.payu.com/pl/standard/co/summary?sessionId= i potem merchantPosId=... timeStamp= ... showLoginDialog=false ... apiToken=...

**Comment by regdos** [comment]
Ten adres jest w przeglądarce i przegląðarka zwraca 403 a nie jakiś klient http?

**Comment by pajso96** [comment]
Google Chrome ,zakładka network. 
...
Request Method:GET
Status Code:403 Forbidden
...

**Comment by pajso96** [comment]
Jezeli to ma znaczenie to dodam ,że w Request Headers nie widzę Authorization na tej stronie.

**Comment by pajso96** [comment]
Aha ,i może to być przyczyną - chociaż wątpie, bo kiedyś korzystałem z tego w podobny sposób.
Przekierowanie odbywa się w ten sposób: 
<script>
    window.location.replace("{{redirect_url}}");
</script>

**Comment by regdos** [comment]
Proszę wyświetlić ``` $response->getResponse()->redirectUri``` i ręcznie wkleić do przeglądarki i sprawdzić czy jest ten sam efekt.

**Comment by pajso96** [comment]
działa ;)
Dzięki wielkie!
