### ISSUE TITLE
Mapping config.php with values from Admin Panel

### ISSUE THREAD

**Issue by marcelijanowski** [PayU/openpayu_php#84]
I'm trying to understand how Admin panel values are mapped with config.php as try with different combination and results are different errors like 
_Error code: 0
Error message: Oauth error: [code=401], [message=invalid_client - Can't find oauthClient with clientId_

```
OpenPayU_Configuration::setMerchantPosId('xxx'); -> POS ID (pos_id) from admin panel
OpenPayU_Configuration::setSignatureKey('xxx'); -> Second key (MD5) from Admin panel

OpenPayU_Configuration::setOauthClientId('xxx'); -> POS ID (pos_id) from admin panel
OpenPayU_Configuration::setOauthClientSecret('xxx');  -> Key (MD5) from admin panel
```

Can some can explain to me which parameter from admin panel should be mapped with parameters in config.php

**Comment by razvan-tache** [comment]
In the admin:
-> Go to My shops
-> Click on the shop name
-> Go on the POS tab
-> Add a REST API POS (if you dont have one already)
-> Click on the POS name for your credentials (https://prnt.sc/i1kg5f)

**Comment by regdos** [comment]
I added info to readme https://github.com/PayU/openpayu_php#configure
