### ISSUE TITLE
Multiple servers with file caching on.

### ISSUE THREAD

**Issue by razvan-tache** [PayU/openpayu_php#85]
For a setup with multiple servers and file caching on, I see that each server gets it's own Token for the same credentials (oAuth). This means that for a set of credentials there can be an unlimited amount of Tokens, each with it's own expiration time.

Is it safe for us to assume this?
Will this be changed?
Is this only sandbox behaviour?
Is it safe to use a multi server configuration with the file cache?

**Comment by lgrzesiak** [comment]
Yes, it is safe to use that. You will get different OAuth tokens and a new token do not invalidate older tokens until they expire. For the moment, we have no plans to change SDK behaviour in this regard.
