### ISSUE TITLE
Problem z utworzeniem zamówienia przy pomocy Guzzle 6.x

### ISSUE THREAD

**Issue by AdrianKuriata** [PayU/openpayu_php#86]
Witam, mam problem z utworzeniem zamówienia za pomocą guzzle. Korzystam z SandBox wersji. Samo połączenie jest poprawne, nie ma problemu z pobraniem dostępnych metod płatności, lecz gdy chcę dodać zamówienie wyskakuje mi błąd

`Client error: POST https://secure.snd.payu.com/api/v2_1/orders/ resulted in a 403 Forbidden response` - nie mam pojęcia o co może chodzić, content-type jest ustawiony na jsona. Jak pisałem wcześniej, łączy się bez problemu. Oto kod, który powinien działać, a nie działa:

```
$client = new Client([
            'base_uri' => 'https://secure.snd.payu.com',
            'form_params' => [
                'grant_type' => 'client_credentials',
                'client_id' => '321991',
                'client_secret' => 'XXX'
            ]
        ]);

        $response = $client->post('/pl/standard/user/oauth/authorize');
        $token = (object) json_decode($response->getBody(), true);

        $orders = $client->post('/api/v2_1/orders/', [
            'headers' => [
                'Authorization' => 'Bearer '.$token->access_token
            ],
            'json' => [
                'customerIp' => $_SERVER['REMOTE_ADDR'],
                'currencyCode' => 'PLN',
                'description' => 'Cos',
                'merchantPosId' => '321991',
                'totalAmount' => '21000',
                'products' => [
                    [
                        'name' => 'Wireless Mouse for Laptop',
                        'unitPrice' => '21000',
                        'quantity' => '1'
                    ]
                ]
            ]
        ]);
```

Z góry dziękuję za pomoc, co do pos_id, też jest na pewno dobry, w innym przypadku nie pobrałbym kodu autoryzacyjnego.

Guzzle - [Klik](https://github.com/guzzle/guzzle)
Edit: // Zastanawiam się, czy nie powinienem napisać na adres techniczny payu?

**Comment by regdos** [comment]
Proszę spróbować czy uderzając bezpośrednio curl-em (tak jak w przykładach z http://developers.payu.com/pl/restapi.html) działa poprawnie. Jeżeli tak to problem jest w składaniu requesta przez guzzla, może brakujące parametry, itp.

Kontakt z adresem technicznym to właściwa droga.

**Comment by AdrianKuriata** [comment]
@regdos Dziękuję za odpowiedź, właśnie ciągnę rozmowę z działem technicznym, na sandboxie nie działa, na testowym produkcyjnym posie zwraca mi kod 200 ale bez danych gdzie trzeba przekierować użytkownika. Spróbuję curlem, tak czy siak dziękuję za odpowiedź, pozdrawiam.

**Comment by AdrianKuriata** [comment]
Gdyby ktoś kiedyś miał z tym problem, wystarczy w instancji tworzonego klienta dodać allow_redirects => false - dlatego, że zwrócona wartość przesyła nam nagłówek Location i próbuje nas przekierować, trzeba wyłączyć możliwość przekierowania, pozdrawiam.

**Comment by si-lens** [comment]
> Gdyby ktoś kiedyś miał z tym problem, wystarczy w instancji tworzonego klienta dodać allow_redirects => false - dlatego, że zwrócona wartość przesyła nam nagłówek Location i próbuje nas przekierować, trzeba wyłączyć możliwość przekierowania, pozdrawiam.

Dzięki za wskazówkę, pomogła mi przy implementacji w Railsach. Wystarczyło ustawić odpowiednik dla HTTParty czyli `follow_redirects: false`
