### ISSUE TITLE
nvm

### ISSUE THREAD

**Issue by rafalveeo** [PayU/openpayu_php#93]
nvm

**Comment by rafalveeo** [comment]
I was TLS 1.0 on my server, which required is TLS 1.2.

**Comment by mossaab** [comment]
Replace following 
`curl_setopt($ch, CURLOPT_SSLVERSION, 3);`
With
`curl_setopt ($ch, CURLOPT_SSLVERSION, 6);`
Should work flawlessly.

**Comment by rafalveeo** [comment]
Thanks for the reply.

From 30 June PayU required only TLS 1.2: http://developers.payu.com/pl/overview.html#encryption

So, I was made the test script:
`$ch = curl_init(); 
                    curl_setopt($ch, CURLOPT_URL, "https://secure.payu.com/api/v2_1/orders"); 
                    curl_setopt ($ch, CURLOPT_SSLVERSION, 6); 
                    var_dump(curl_exec($ch)); 
                    var_dump(curl_error($ch));`
And see this error.

I have SSL certificate on my server in TLS 1.0 version and i must change it.
