### ISSUE TITLE
Brak wersji v2.2.10 w packagist 

### ISSUE THREAD

**Issue by frasiek** [PayU/openpayu_php#96]
https://packagist.org/packages/openpayu/openpayu nie ma wersji 2.2.10

**Comment by regdos** [comment]
Nowa wersja powinna się sama pojawić, sprawdzamy dlaczego nie pojawiła się.

**Comment by regdos** [comment]
Wygląda na problem po stronie packagista https://twitter.com/packagist/status/1026435915542085632

**Comment by regdos** [comment]
Wersja 2.2.10 jest już dostępna przez packagist https://packagist.org/packages/openpayu/openpayu
